### ISSUE TITLE
Research about MST and NFC

### ISSUE THREAD

**Issue by 320834** [nyu-software-engineering/fall-2019-course-scheduler#10]
Magnetic Secure Transmission (MST) and Near Field Communication (NFC) are protocols used to transmit magnetic waves from phones. These technologies are used to simulate a card with a chip so that the phone can act as the card through magnetic waves. 

We need to do more research on this topic.
- [ ] Check what type of card NYU uses and if there exists a chip inside the card
- [ ] Figure out if there exists a library that translate the information of the physical card into a magnetic form

**Comment by sm7515** [comment]
no longer need NFC
