### ISSUE TITLE
As a NYU student/faculty, I want to enter the information on NYU id card, so that this info can produce magnetic waves to simulate magnetic strip on a card

### ISSUE THREAD

**Issue by 320834** [nyu-software-engineering/fall-2019-course-scheduler#6]
Acceptance Criteria
- [ ] The NYU student/faculty uploads their card information.
- [ ] The program stores the information and converts that info to data that can emit magnetic waves
- [ ] Phone will produce magnetic waves to be used on card scanners in buildings

**Comment by shellycao123** [comment]
Probably you want to hide the technical details from the user, like how the card works in place of the physical card.
